CREATE TABLESPACE PINACOTECAS1
DATAFILE
  'C:\ORACLE\EJEMPLOS\PINACOTECAS1-1.ORA' SIZE 1 M,
  'C:\ORACLE\EJEMPLOS\PINACOTECAS1-2.ORA' SIZE 500 K
DEFAULT STORAGE (INITIAL 10K NEXT 10K PCTINCREASE 25);

CREATE USER PINACOTECAS1
IDENTIFIED BY  PINACOTECAS1
DEFAULT TABLESPACE  PINACOTECAS1
QUOTA UNLIMITED ON  PINACOTECAS1;

GRANT DBA TO PINACOTECAS1;


CREATE TABLE CUADROS(
ID_CUADRO VARCHAR2(5),
N_CUADRO VARCHAR2(75),
ANCHO VARCHAR2(10),
ALTO VARCHAR2(10),
F_PINTADO VARCHAR2(20),
TECNICA VARCHAR2(35),
FK_PINAC VARCHAR2(5)
);
CREATE TABLE PINTORES(
ID_PINTOR VARCHAR2(5),
N_PINTOR VARCHAR2(60),
CIUDAD VARCHAR2(35),
PAIS VARCHAR2(25),
FECHA_N DATE,
FECHA_F DATE
);
CREATE TABLE MECENAS(
ID_MECENAS VARCHAR2(5),
N_MECENAS VARCHAR2(30),
CIUDAD_NAC VARCHAR2(30),
PAIS VARCHAR2(25)
);
CREATE TABLE ESCUELAS(
ID_ESCUELA VARCHAR2(5),
N_ESCUELA VARCHAR2(30),
PAIS VARCHAR2(25),
FECHA_APARICION DATE
);
CREATE TABLE CUADROS_PINTORES(
ID_FK_CUADRO VARCHAR2(5),
FK_PINTOR VARCHAR2(5)
);
CREATE TABLE PINTORES_ESCUELAS(
ID_FK_PINTOR VARCHAR2(5),
FK_ESCUELA VARCHAR2(5)
);
CREATE TABLE MECENAZGO(
ID_FK_PINTOR VARCHAR2(5),
ID_FK_MECENAS VARCHAR2(5),
ID_FECHA_INICIO DATE,
FECHA_FINAL DATE
);
CREATE TABLE MAESTROS(
ID_FK_PINTOR VARCHAR2(5),
FK_MAESTRO VARCHAR2(5)
);

-- CREAR CLAVES PRIMARIAS
ALTER TABLE PINACOTECAS			ADD CONSTRAINT PK_PINACOTECAS			PRIMARY KEY (ID_PINACOTECA);
ALTER TABLE CUADROS				ADD CONSTRAINT PK_CUADROS				PRIMARY KEY (ID_CUADRO);
ALTER TABLE PINTORES			ADD CONSTRAINT PK_PINTORES				PRIMARY KEY (ID_PINTOR);
ALTER TABLE ESCUELAS			ADD CONSTRAINT PK_ESCUELAS				PRIMARY KEY (ID_ESCUELA);
ALTER TABLE MECENAS				ADD CONSTRAINT PK_MECENAS				PRIMARY KEY (ID_MECENAS);
ALTER TABLE MECENAZGO			ADD CONSTRAINT PK_MECENAZGO				PRIMARY KEY (ID_FK_PINTOR,ID_FK_MECENAS,ID_FECHA_INICIO);
ALTER TABLE MAESTROS			ADD CONSTRAINT PK_MAESTRO				PRIMARY KEY (ID_FK_PINTOR);
ALTER TABLE PINTORES_ESCUELAS	ADD CONSTRAINT PK_PINTORES_ESCUELAS		PRIMARY KEY (ID_FK_PINTOR);
ALTER TABLE CUADROS_PINTORES	ADD CONSTRAINT PK_CUADROS_PINTORES		PRIMARY KEY (ID_FK_CUADRO);

-- CREAR CLAVES FOR�NEAS
ALTER TABLE CUADROS				ADD CONSTRAINT FK_CUADROS_PINACOTECAS	FOREIGN KEY (FK_PINAC)		REFERENCES PINACOTECAS;
ALTER TABLE MECENAZGO			ADD CONSTRAINT FK_MECENAZGO_PINTORES	FOREIGN KEY (ID_FK_PINTOR)	REFERENCES PINTORES;
ALTER TABLE MECENAZGO			ADD CONSTRAINT FK_MECENAZGO_MECENAS		FOREIGN KEY (ID_FK_MECENAS)	REFERENCES MECENAS;
ALTER TABLE MAESTROS			ADD CONSTRAINT FK_MAESTROS_PINTORES_P	FOREIGN KEY (ID_FK_PINTOR)	REFERENCES PINTORES;
ALTER TABLE MAESTROS			ADD CONSTRAINT FK_MAESTROS_PINTORES_M	FOREIGN KEY (FK_MAESTRO)	REFERENCES PINTORES;
ALTER TABLE PINTORES_ESCUELAS	ADD CONSTRAINT FK_PINTORES_ESCUELAS_P	FOREIGN KEY (ID_FK_PINTOR)	REFERENCES PINTORES;
ALTER TABLE PINTORES_ESCUELAS	ADD CONSTRAINT FK_PINTORES_ESCUELAS_E	FOREIGN KEY (FK_ESCUELA)	REFERENCES ESCUELAS;
ALTER TABLE CUADROS_PINTORES	ADD CONSTRAINT FK_PINTORES_ESCUELAS_C	FOREIGN KEY (ID_FK_CUADRO)	REFERENCES CUADROS;
ALTER TABLE CUADROS_PINTORES	ADD CONSTRAINT FK_PINTORES_ESCUELAS_PIN	FOREIGN KEY (FK_PINTOR)		REFERENCES PINTORES;





-- PINACOTECAS
INSERT INTO PINACOTECAS VALUES('LOUVR','MUSEO DEL LOUVRE','RUE DE RIVOLI, S/N','PARÍS','FRANCIA',NULL);
INSERT INTO PINACOTECAS VALUES('MUPRA','MUSEO DEL PRADO','PASEO DEL PRADO, S/N','MADRID','ESPAÑA',NULL);
INSERT INTO PINACOTECAS VALUES('ASHMU','ASHMOLEAN MUSEUM','BEAUMONT ST','OXFORD','INGLATERRA',NULL);
INSERT INTO PINACOTECAS VALUES('MURES','MUSEO REINA SOFÍA','CALLE SANTA ISABEL, 52','MADRID','ESPAÑA',NULL);
INSERT INTO PINACOTECAS VALUES('MUBAS','MUSEO DE BELLAS ARTES DE SEVILLA','PLAZA DEL MUSEO, S/N','SEVILLA','ESPAÑA',NULL);
INSERT INTO PINACOTECAS VALUES('UFFIZ','GALERÍA UFFIZI','PIAZZALE DEGLI UFFIZI','FLORENCIA','ITALIA',NULL);

-- CUADROS
INSERT INTO CUADROS VALUES ('AAC01','ANUNCIACIÓN','98,4 cm','217 cm','1473-1475','ÓLEO SOBRE TABLA','UFFIZ');
INSERT INTO CUADROS VALUES ('AAC02','LA ADORACIÓN DE LOS MAGOS','246 cm','243 cm','1481-1482','ÓLEO SOBRE TABLA','UFFIZ');
INSERT INTO CUADROS VALUES ('AAC03','LA GIOCONDA','77 cm','53 cm','1503-1519','ÓLEO SOBRE TABLA','LOUVR');
INSERT INTO CUADROS VALUES ('AAC04','EL BAUTISMO DE CRISTO','177 cm','171 cm','1475-1478','ÓLEO SOBRE TABLA','UFFIZ');
INSERT INTO CUADROS VALUES ('AAC05','LAS TRES GRACIAS','221 cm','181 cm','CIRCA 1635','ÓLEO SOBRE LIENZO','MUPRA');
INSERT INTO CUADROS VALUES ('AAC06','VULCANO FORJANDO LOS RAYOS DE JÚPITER','181 cm','98 cm','CIRCA 1676','ÓLEO SOBRE LIENZO','MUPRA');
INSERT INTO CUADROS VALUES ('AAC07','LAS MENINAS','3,2 m','2,76 m','1656','ÓLEO SOBRE LIENZO','MUPRA');
INSERT INTO CUADROS VALUES ('AAC08','RETRATO DE CRISTÓBAL SUÁREZ DE RIBERA','207 cm','148 cm','1620','ÓLEO SOBRE LIENZO','MUBAS');
INSERT INTO CUADROS VALUES ('AAC09','SAN HUGO EN EL REFECTORIO DE LOS CARTUJOS','262 cm','307 cm','1630-1635','ÓLEO SOBRE LIENZO','MUBAS');
INSERT INTO CUADROS VALUES ('AAC10','VISIÓN DE SAN PEDRO NOLASCO','179 cm','223 cm','1629','ÓLEO SOBRE LIENZO','MUPRA');
INSERT INTO CUADROS VALUES ('AAC11','EL NACIMIENTO DE VENUS','278,5 cm','109,6','1483-1485','TEMPLE SOBRE MADERA','UFFIZ');
INSERT INTO CUADROS VALUES ('AAC12','RETRATO DE BALTHAZAR CASTIGLIONE','82 cm','67 cm','1514-1515','ÓLEO SOBRE LIENZO','LOUVR');
INSERT INTO CUADROS VALUES ('AAC13','EL GUERNICA','349,3 cm','777,6 cm','1937','ÓLEO SOBRE LIENZO','MURES');
INSERT INTO CUADROS VALUES ('AAC14','JOVEN CON LORO','72 cm','28,3 cm','1758-1760','ÓLEO SOBRE LIENZO','ASHMU');
INSERT INTO CUADROS VALUES ('AAC15','EL JARDÍN DE LAS DELICIAS','220 cm','195 cm','1480-1490','ÓLEO SOBRE TABLA','MUPRA');	
INSERT INTO CUADROS VALUES ('AAC16','BETSABE EN EL BAÑO','142 cm','142 cm','1654','ÓLEO SOBRE LIENZO','LOUVR');
INSERT INTO CUADROS VALUES ('AAC17','EL CABALLERO DE LA MANO EN EL PECHO','81,8 cm','65,8 cm','CIRCA 1580','ÓLEO SOBRE LIENZO','MUPRA');
INSERT INTO CUADROS VALUES ('AAC18','FUSILAMIENTOS DEL 3 DE MAYO','268 cm','347 cm','1814','ÓLEO SOBRE LIENZO','MUPRA');
INSERT INTO CUADROS VALUES ('AAC19','SAGRADA FAMILIA','120 cm','120 cm','1506-1508','ÓLEO Y TEMPLE SOBRE MADERA','UFFIZ');

-- PINTORES
INSERT INTO PINTORES VALUES ('ANDVE','ANDREA VERROCCHIO',NULL,NULL,NULL,NULL);
INSERT INTO PINTORES VALUES ('LEODV','LEONARDO DA VINCI',NULL,NULL,NULL,NULL);
INSERT INTO PINTORES VALUES ('RAFSA','RAFFAELLO SANZIO',NULL,NULL,NULL,NULL);
INSERT INTO PINTORES VALUES ('MICHE','MICHELANGELO BUONARROTI',NULL,NULL,NULL,NULL);
INSERT INTO PINTORES VALUES ('PERUG','PIETRO PERUGINO',NULL,NULL,NULL,NULL);
INSERT INTO PINTORES VALUES ('BOTIC','SANDRO BOTTICELLI',NULL,NULL,NULL,NULL);
INSERT INTO PINTORES VALUES ('ZURBA','FRANCISCO DE ZURBARÁN',NULL,NULL,NULL,NULL);
INSERT INTO PINTORES VALUES ('DIEGO','DIEGO VELÁZQUEZ',NULL,NULL,NULL,NULL);
INSERT INTO PINTORES VALUES ('GIOVA','GIOVANNI BATTISTA TIEPOLO',NULL,NULL,NULL,NULL);
INSERT INTO PINTORES VALUES ('GHIRL','DOMENICO GHIRLANDAIO',NULL,NULL,NULL,NULL);
INSERT INTO PINTORES VALUES ('PICAS','PABLO PICASSO',NULL,NULL,NULL,NULL);
INSERT INTO PINTORES VALUES ('FGOYA','FRANCISCO DE GOYA',NULL,NULL,NULL,NULL);
INSERT INTO PINTORES VALUES ('GRECO','EL GRECO',NULL,NULL,NULL,NULL);
INSERT INTO PINTORES VALUES ('BOSCO','EL BOSCO',NULL,NULL,NULL,NULL);
INSERT INTO PINTORES VALUES ('REMBR','REMBRANDT',NULL,NULL,NULL,NULL);
INSERT INTO PINTORES VALUES ('LAZAR','GREGORIO LAZZARINI',NULL,NULL,NULL,NULL);
INSERT INTO PINTORES VALUES ('RUBEN','PETER PABLO RUBENS',NULL,NULL,NULL,NULL);

-- MECENAS
INSERT INTO MECENAS VALUES('FEH60','FELIPE EL HERMOSO','BRUJAS','HOLANDA');
INSERT INTO MECENAS VALUES('GD060','GERRIT DOU','LEIDEN','ALEMANIA');
INSERT INTO MECENAS VALUES('MC370','CARLOS III','MADRID','ESPAÑA');
INSERT INTO MECENAS VALUES('MIC70','ISABEL LA CATOLICA','MADRIGAL DE LAS ALTAS TORRES','ESPAÑA');
INSERT INTO MECENAS VALUES('MFS70','FELIPE II','VALLADOLID','ESPAÑA');
INSERT INTO MECENAS VALUES('JDF70','JUAN DE FONSECA','TORO - ZAMORA','ESPAÑA');
INSERT INTO MECENAS VALUES('DDA70','DUQUE DE ALCALA','ALCALA DE HENARES','ESPAÑA');
INSERT INTO MECENAS VALUES('DDO70','DUQUES DE OSUNA','MADRID','ESPAÑA');
INSERT INTO MECENAS VALUES('JL001','JULIO II','ALBISSOLA','ITALIA');
INSERT INTO MECENAS VALUES('LX002','LEON X','FLORENCIA','ITALIA');
INSERT INTO MECENAS VALUES('LM003','LORENZO DE MEDICIS','FLORENCIA','ITALIA');
INSERT INTO MECENAS VALUES('M0100','FEDERICO II DE MONTEFELTRO','ROMA','ITALIA');
INSERT INTO MECENAS VALUES('M0300','GERTRUDE STEIN','PENSILVANIA','ESTADOS UNIDOS DE AMERICA');
INSERT INTO MECENAS VALUES('M0400','FRANCISCO I DE FRANCIA','COGNAC','FRANCIA');
INSERT INTO MECENAS VALUES('M0500','CONDE DE BEROLDINGEN','BEROLDINGEN','SUIZA');
INSERT INTO MECENAS VALUES('M0600','FELIPE IV','VALLADOLID','ESPAÑA');
INSERT INTO MECENAS VALUES('M0700','REINA MARIA DE MEDICI','FLORENCIA','ITALIA');

-- ESCUELAS
INSERT INTO ESCUELAS VALUES ('EHOLA','ESCUELA HOLANDESA','HOLANDA','20/11/1650');
INSERT INTO ESCUELAS VALUES ('EBRUJ','ESCUELA DE BRUJAS','BELGICA','06/07/1460');
INSERT INTO ESCUELAS VALUES ('EFLOR','ESCUELA FLORENTINA','ITALIA','09/06/1250');
INSERT INTO ESCUELAS VALUES ('EROMA','ESCUELA DE ROMA','ITALIA','08/12/1445');
INSERT INTO ESCUELAS VALUES ('EVENE','ESCUELA VENECIANA','ITALIA','18/09/1530');
INSERT INTO ESCUELAS VALUES ('ECUBI','ESCUELA CUBISTA ESPAÑOLA','ESPAÑA','10/12/1910');
INSERT INTO ESCUELAS VALUES ('EMANI','ESCUELA MANIERISTA ITALIANA','ITALIA','09/11/1600');
INSERT INTO ESCUELAS VALUES ('EBASE','ESCUELA BARROCA SEVILLANA','ESPAÑA','07/03/1600');
INSERT INTO ESCUELAS VALUES ('EFLAM','ESCUELA FLAMENCA HOLANDESA','HOLANDA','19/11/1525');
INSERT INTO ESCUELAS VALUES ('EROCO','ESCUELA ROCOCO ITALIANA','ITALIA','01/02/1700');
INSERT INTO ESCUELAS VALUES ('ETENE','ESCUELA TENEBRISTA ESPAÑOLA','ESPAÑA','15/09/1660');
INSERT INTO ESCUELAS VALUES ('EROES','ESCUELA ROCOCO ESPAÑOLA','ESPAÑA','07/07/1700');

-- CUADROS-PINTORES
INSERT INTO CUADROS_PINTORES VALUES('AAC01','LEODV');
INSERT INTO CUADROS_PINTORES VALUES('AAC02','LEODV');
INSERT INTO CUADROS_PINTORES VALUES('AAC03','LEODV');
INSERT INTO CUADROS_PINTORES VALUES('AAC04','ANDVE');
INSERT INTO CUADROS_PINTORES VALUES('AAC05','RUBEN');
INSERT INTO CUADROS_PINTORES VALUES('AAC06','RUBEN');
INSERT INTO CUADROS_PINTORES VALUES('AAC07','DIEGO');
INSERT INTO CUADROS_PINTORES VALUES('AAC08','DIEGO');
INSERT INTO CUADROS_PINTORES VALUES('AAC09','ZURBA');
INSERT INTO CUADROS_PINTORES VALUES('AAC10','ZURBA');
INSERT INTO CUADROS_PINTORES VALUES('AAC11','BOTIC');
INSERT INTO CUADROS_PINTORES VALUES('AAC12','RAFSA');
INSERT INTO CUADROS_PINTORES VALUES('AAC13','PICAS');
INSERT INTO CUADROS_PINTORES VALUES('AAC14','GIOVA');
INSERT INTO CUADROS_PINTORES VALUES('AAC15','BOSCO');
INSERT INTO CUADROS_PINTORES VALUES('AAC16','REMBR');
INSERT INTO CUADROS_PINTORES VALUES('AAC17','GRECO');
INSERT INTO CUADROS_PINTORES VALUES('AAC18','FGOYA');
INSERT INTO CUADROS_PINTORES VALUES('AAC19','MICHE');

-- PINTORES-ESCUELAS
INSERT INTO PINTORES_ESCUELAS VALUES ('ANDVE','EFLOR');
INSERT INTO PINTORES_ESCUELAS VALUES ('LEODV','EROMA');
INSERT INTO PINTORES_ESCUELAS VALUES ('RAFSA','EROMA');
INSERT INTO PINTORES_ESCUELAS VALUES ('MICHE','EROMA');
INSERT INTO PINTORES_ESCUELAS VALUES ('PERUG','EFLOR');
INSERT INTO PINTORES_ESCUELAS VALUES ('BOTIC','EFLOR');
INSERT INTO PINTORES_ESCUELAS VALUES ('ZURBA','EBASE');
INSERT INTO PINTORES_ESCUELAS VALUES ('DIEGO','EBASE');
INSERT INTO PINTORES_ESCUELAS VALUES ('GIOVA','EVENE');
INSERT INTO PINTORES_ESCUELAS VALUES ('GHIRL','EFLOR');
INSERT INTO PINTORES_ESCUELAS VALUES ('PICAS','ECUBI');
INSERT INTO PINTORES_ESCUELAS VALUES ('FGOYA','EROES');
INSERT INTO PINTORES_ESCUELAS VALUES ('GRECO','EVENE');
INSERT INTO PINTORES_ESCUELAS VALUES ('BOSCO','EFLAM');
INSERT INTO PINTORES_ESCUELAS VALUES ('REMBR','EHOLA');
INSERT INTO PINTORES_ESCUELAS VALUES ('LAZAR','EVENE');
INSERT INTO PINTORES_ESCUELAS VALUES ('RUBEN','EFLAM');

-- MECENAZGO
INSERT INTO MECENAZGO VALUES('REMBR','GD060','02/05/1503','02/06/1520');
INSERT INTO MECENAZGO VALUES('BOSCO','FEH60','03/06/1496','03/07/1507');
INSERT INTO MECENAZGO VALUES('GIOVA','MC370','01/08/1630','01/09/1650');
INSERT INTO MECENAZGO VALUES('GRECO','MFS70','06/09/1580','06/10/1600');
INSERT INTO MECENAZGO VALUES('DIEGO','JDF70','02/02/1630','04/06/1650');
INSERT INTO MECENAZGO VALUES('FGOYA','DDO70','30/01/1785','30/03/1810');
INSERT INTO MECENAZGO VALUES('MICHE','JL001','08/04/1496','12/06/1506');
INSERT INTO MECENAZGO VALUES('RAFSA','JL001','09/02/1508','30/06/1513');
INSERT INTO MECENAZGO VALUES('RAFSA','LX002','21/06/1512','23/08/1520');
INSERT INTO MECENAZGO VALUES('BOTIC','LM003','25/01/1443','02/11/1492');
INSERT INTO MECENAZGO VALUES('MICHE','LM003','18/05/1489','20/05/1492');
INSERT INTO MECENAZGO VALUES('PICAS','M0300','23/12/1910','21/03/1915');
INSERT INTO MECENAZGO VALUES('LEODV','M0400','06/11/1503','10/10/1508');
INSERT INTO MECENAZGO VALUES('ZURBA','M0500','11/02/1625','01/05/1629');
INSERT INTO MECENAZGO VALUES('DIEGO','M0600','05/05/1638','02/06/1645');
INSERT INTO MECENAZGO VALUES('RUBEN','M0700','10/05/1620','01/09/1625');

-- MAESTROS
INSERT INTO MAESTROS VALUES ('ANDVE','DONAT');
INSERT INTO MAESTROS VALUES ('LEODV','ANDVE');
INSERT INTO MAESTROS VALUES ('RAFSA','PERUG');
INSERT INTO MAESTROS VALUES ('MICHE','GHIRL');
INSERT INTO MAESTROS VALUES ('PERUG','ANDVE');
INSERT INTO MAESTROS VALUES ('GIOVA','LAZAR');